using System;
using MediNexus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediNexus.Infrastructure.Migrations
{
    [DbContext(typeof(MediNexusDbContext))]
    [Migration("20260628000000_Fix_Cie10CodesTable")]
    /// <inheritdoc />
    public partial class Fix_Cie10CodesTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create Cie10Codes if it was lost (dropped by cleanup in a previous migration run)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Cie10Codes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Codigo"" character varying(10) NOT NULL,
                    ""Descripcion"" character varying(500) NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_Cie10Codes"" PRIMARY KEY (""Id"")
                );");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Cie10Codes_Codigo""
                ON ""Cie10Codes"" (""Codigo"");");

            // Re-add FK from Diagnosticos to Cie10Codes if it was dropped by CASCADE
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint c
                        JOIN pg_class t ON t.oid = c.conrelid
                        JOIN pg_class r ON r.oid = c.confrelid
                        WHERE t.relname = 'AnalisisDiagnosticosPlan_HCinicial_Diagnosticos'
                          AND r.relname = 'Cie10Codes'
                          AND c.contype = 'f'
                    ) AND EXISTS (
                        SELECT 1 FROM pg_class WHERE relname = 'AnalisisDiagnosticosPlan_HCinicial_Diagnosticos' AND relkind = 'r'
                    ) THEN
                        ALTER TABLE ""AnalisisDiagnosticosPlan_HCinicial_Diagnosticos""
                        ADD CONSTRAINT ""FK_AnalisisDiagnosticosPlan_HCinicial_Diagnosticos_IdCie10""
                        FOREIGN KEY (""IdCie10"") REFERENCES ""Cie10Codes"" (""Id"")
                        ON DELETE RESTRICT;
                    END IF;
                END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "Cie10Codes");
        }
    }
}
